# Use an official Node.js runtime as a parent image for building
FROM node:20

# Set the working directory in the container
WORKDIR /usr/src/app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Expose the development port (usually 3000 for React)
EXPOSE 3000

# Run the application in development mode
CMD ["npm", "start","--reset-cache"]
